#! /bin/ash
# start a shell
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PATH=$PATH:/rlive/bin:/rlive/usr/bin:/rlive/sbin:/rlive/usr/sbin
export PATH
cd /etc
ldconfig		# should work here
mount -a 
ash installmod
while true
do
	echo; echo;
	echo Welcome to the Gwynux main menu
	echo type: cdboot to mount the cd
	echo type: usbboot to mount the usb iso image
	echo type: shell for a shell
	echo type: init to exec init 
	echo
	echo After the media is mounted
	echo Type setup to begin
	echo
	echo 
	read ANS REST
	case "$ANS" in
		shell)  exec bash ;;	
		cdboot) exec ./cdboot ;;
		usbboot) exec ./usbboot ;;
		init) exec /sbin/init ;;
		*) echo Unrecognized Command; echo ;;
	esac
done
