#! /bin/ash
# start init
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PATH=$PATH:/rlive/bin:/rlive/usr/bin:/rlive/sbin:/rlive/usr/sbin
export PATH
cd /etc
ldconfig		# should work here
mount -a 
ash installmod
echo Starting init
exec  /sbin/init 		
