#!/bin/sh
# start stop gdm
#
case "$1" in
'start')
	if [ -f /usr/local/bin/gdm ]
	then
  		exec /usr/local/bin/gdm 
		exit $?
	fi
	;;
'stop')
	if /usr/bin/pgrep gdm
	then
		pkill gdm
		exit $?
	fi
	;;
*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 1
