#!/bin/sh
# start stop local
#
case "$1" in
'start')
  	if [ -x /usr/local/sbin/local.start ]
	then
		/usr/local/sbin/local.start
		exit 0
	fi
	;;
'stop')
  	if [ -x /usr/local/sbin/local.stop ]
	then
		/usr/local/sbin/local.stop 
		exit 0
	fi
	;;
*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 1
