#!/bin/sh
# start stop inetd
#
case "$1" in
'start')
  	if [ -x /usr/sbin/inetd ]
	then
		/usr/sbin/inetd
		exit $?
	fi
	;;
'stop')
  	if [ -x /usr/sbin/inetd ]
	then
		/usr/bin/pkill inetd
		exit $?
	fi
	;;
*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 1
