#!/bin/sh
# start stop named
#
case "$1" in
'start')
  	if [ -f /etc/named.conf ]
	then
		/usr/sbin/named
		exit $?
	fi
	;;
'stop')
  	if [ -f /etc/named.conf ]
	then
		/usr/bin/pkill named
		exit $?
	fi
	;;
*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 1
