#! /bin/sh
# Do basic gwynux install
#
if [ $# -eq 0 ]
then 
	echo Usage: $0 '<install-device> [loopsize]'
	exit
fi
if  echo "X$2" | grep '^X[0-9][0-9]*$' > /dev/null 
then
	LOOP='-o loop'
	dd if=/dev/zero of=$1 bs=1k count=$2
else	
	LOOP=""
fi
#
# Confirm install
#
echo This will destroy the current contents of $1
echo Ready to install on $1 type '"yes"' to continue ?
read input
if [ \"$input\" != '"yes"' ]
then 
	echo Install aborted
	exit
fi
#
# Make an ext3 filesystem
#
if mke2fs -j $1
then
	mount $LOOP $1 /mnt
else
	echo Unable to mount filesystem
	exit
fi
cd /mnt
#
# Do a live copy 
#
echo Performing live install
( cd /cdrom/live/ ; tar cf - . ) | tar xf -
# 
# install boot loader and fstab
#
# install fstab and lilo
/sbin/mkfstab $1 > etc/fstab
/sbin/mklilo $1 > etc/lilo.conf
echo Shall I install the boot loader on the install drive? [y/n]?
read ans rest
if [ "X$ans" == "Xy" ]
then
	ln -sf /mnt/boot /boot
	ln -sf /mnt/bzImage /bzImage
	/sbin/lilo -C /mnt/etc/lilo.conf
fi
cd /
umount /mnt
