#! /bin/sh
# perform a live dir install
if [ $# -lt 1 ]
then 
	echo Usage: $0 '<install-source> [<install-target>]'
	exit
fi
# default target to live
if [ $# -lt 2 ]
then 
	TARGET=live
else
	TARGET=$2
fi
echo Target directory is $TARGET
rm -r $TARGET 2>/dev/null
mkdir $TARGET
cd $TARGET 
mkdir pkg 2>/dev/null
for FILE in ../$1/gwynux/basic/*.tgz 
do
NAME=`echo $FILE | sed 's/.*\///' | sed 's/\.bin.tgz//' | sed 's/\.tgz//'` 
echo installing $NAME
tar zxvf $FILE > pkg/$NAME
[ -f install/doinst.sh ] && sh install/doinst.sh
[ -f install/doinst.sh ] && mv install/doinst.sh install/doinst.sh.$NAME
rm -f install/doinst.sh
done
# install fstab and lilo
/sbin/mkfstab $TARGET > etc/fstab
/sbin/mklilo $TARGET > etc/lilo.conf
