#! /bin/sh
# Remove a package
if [ X$1 = X ]
then 
	echo "usage: $0 <packagenamefile>"
	exit
fi
for file in `cat $1`
do
	if [ -f /$file -o -L /$file ]
		then
		echo removing $file
		rm /$file 
		fi
done
for file in `cat $1`
do
	if [ -d /$file ]
		then
		if rmmdir /$file  2>/dev/null
			then
			echo removing $file
			fi
		fi
done
rm $1
