# Generate invoice/expense forms from input record
#  input: $1=N $2=type $3=date $4=who $5=fromac $6=amount $7=gst $8=pst $9=toac 
	{ ca=substr($5,1,4); cb=substr($9,1,4)
	fromsel[ca]="selected" ; tosel[cb]="selected" }
$2 == "E" {
print "<html>"
print "<head><title>Toadware Technologies Inc. -Accounting System</title></head>"
print "<body>" 
print "<H1>Accounting System - Expense Records</H1>"
print "Enter expense entries and click submit."	 
print "Click reset to clear form."
print "<p>"
print "Enter GST ammount if supplied or 0 if no GST."
print "Leave GST blank to calculate."
print "<br>"
print "Enter PST ammount of 0 if no PST."
print "Leave PST blank if included."
print "<hr>"
print "<form action=\"/cgi-bin/account/" type "\" method=\"post\">"
print "<pre>"
print "  	<input type=hidden name=type value=\"" $1 "\">"
print "  	<input type=hidden name=type size=1 value=E>"
print "Date:    <input type=text name=date value=\"" $3 "\" size=6>"
print "Paid to: <input type=text name=paidto value=\"" $4 "\" size=40>"
print "Paid fr: <select name=fracct size=1>"
print "<option " fromsel["2000"] "> 2000  Accrued Expenses" 
print "<option " fromsel["1000"] "> 1000  Bank General" 
print "<option " fromsel["2300"] "> 2300  Accounts Payable" 
print "</select>"
print "Ammount: <input type=text name=ammount value=\"" $6 "\" size=20>"
print "GST:     <input type=text name=gst value=\"" $7 "\" size=20>"
print "PST:     <input type=text name=pst value=\"" $8 "\" size=20>"
print "Account: <select name=account size=1>"
print "<option " tosel["1500"] "> 1500  Furniture & Fixtures    "
print "<option " tosel["1510"] "> 1510  Equipment               "
print "<option " tosel["1520"] "> 1520  Reference Library       "
print "<option " tosel["1530"] "> 1530  Vehicle(s)              "
print "<option " tosel["1540"] "> 1540  Computer Hardware       "
print "<option " tosel["1550"] "> 1550  Computer Software       "
print "<option " tosel["1560"] "> 1560  Chattels                "
print "<option " tosel["2000"] "> 2000  Accrued Expenses        "
print "<option " tosel["2300"] "> 2300  Accounts Payable        "
print "<option " tosel["5100"] "> 5100  Purchases for Resale    "
print "<option " tosel["6000"] "> 6000  Professional Services   "
print "<option " tosel["6010"] "> 6010  Secretarial Services    "
print "<option " tosel["6030"] "> 6030  Commissions             "
print "<option " tosel["6050"] "> 6050  Sub-Contracted Services "
print "<option " tosel["6100"] "> 6100  Rent                  "
print "<option " tosel["6105"] "> 6105  Mortgage Interest       "
print "<option " tosel["6110"] "> 6110  Condominium Fees        "
print "<option " tosel["6115"] "> 6115  Property Taxes          "
print "<option " tosel["6120"] "> 6120  Insurance               "
print "<option " tosel["6125"] "> 6125  Utilities               "
print "<option " tosel["6130"] "> 6130  Repairs & Maintenance   "
print "<option " tosel["6150"] "> 6150  Other Building Expenses "
print "<option " tosel["6195"] "> 6195  Personal Use            "
print "<option " tosel["6200"] "> 6200  Business Taxes & Permits"
print "<option " tosel["6205"] "> 6205  Telecommunications      "
print "<option " tosel["6210"] "> 6210  Postage, Courier & Frght"
print "<option " tosel["6215"] "> 6215  Materials & Supplies    "
print "<option " tosel["6220"] "> 6220  Equipment Rent & Repair "
print "<option " tosel["6225"] "> 6225  Liab or Bus Insurance   "
print "<option " tosel["6230"] "> 6230  Printing & Copying      "
print "<option " tosel["6235"] "> 6235  Ref Books & Magazines   "
print "<option " tosel["6240"] "> 6240  Stationery & Cards      "
print "<option " tosel["6250"] "> 6250  Other Office Expenses   "
print "<option " tosel["6300"] "> 6300  Loan Interest           "
print "<option " tosel["6305"] "> 6305  Bank Charges            "
print "<option " tosel["6310"] "> 6310  Accounting & Legal Fees "
print "<option " tosel["6315"] "> 6315  Association Dues        "
print "<option " tosel["6320"] "> 6320  Business Promotion      "
print "<option " tosel["6325"] "> 6325  Travel                  "
print "<option " tosel["6330"] "> 6330  Conferences & Seminars  "
print "<option " tosel["6335"] "> 6335  Advertising             "
print "<option " tosel["6340"] "> 6340  Small Tools             "
print "<option " tosel["6350"] "> 6350  Bad Debts               "
print "<option " tosel["6360"] "> 6360  Miscellaneous           "
print "<option " tosel["6400"] "> 6400  Garaging & Parking      "
print "<option " tosel["6405"] "> 6405  Leasing                 "
print "<option " tosel["6410"] "> 6410  Gasoline                "
print "<option " tosel["6420"] "> 6420  Plates & Permits        "
print "<option " tosel["6425"] "> 6425  Repairs & Maintenance   "
print "<option " tosel["6430"] "> 6430  Financing Charges       "
print "<option " tosel["6435"] "> 6435  Washing & Waxing        "
print "<option " tosel["6450"] "> 6450  Other Vehicle Expenses  "
print "<option " tosel["6495"] "> 6495  Personal Use            "
print "<option " tosel["6900"] "> 6900  Depreciation            "
print "</select>"
print "File:    <input type=file name=file size=20>"
print "</pre>"
print "<input type=submit value=\"Submit entry\">"
print "<input type=reset value=\"Clear entry\">"
print "</form>"
print "<hr>"
print "</body></html>"
}
$2 == "I" {
print "<html>"
print "<head><title>Toadware Technologies Inc. -Accounting System</title></head>"
print "<body>"
print "<H1>Accounting System - Invoice Records</H1>"
print "Enter invoice entries and click submit."
print "Click reset to clear form."
print "<p>"
print "Enter GST/PST ammount if supplied or 0 if none."
print "Leave blank to calculate."
print "<hr>"
print "<form action=\"/cgi-bin/account/" type "\" method=\"post\">"
print "<pre>"
print "  	<input type=hidden name=type value=\"" $1 "\">"
print "	 	<input type=hidden name=type size=1 value=I>"
print "Date:    <input type=text name=date value=\"" $3 "\" size=6>"
print "From:    <input type=text name=paidto value=\"" $4 "\" size=40>"
print "To acct: <select name=toacct size=1>"
print "<option " fromsel["1000"] "> 1000  Bank General"
print "<option " fromsel["2000"] "> 2000  Accrued Expenses"
print "<option " fromsel["1200"] "> 1200  Accounts Receivable     "
print "<option " fromsel["2100"] "> 2100  GST Collected           "
print "</select>"
print "Ammount: <input type=text name=ammount value=\"" $6 "\" size=20>"
print "GST:     <input type=text name=gst value=\"" $7 "\" size=20>"
print "PST:     <input type=text name=pst value=\"" $8 "\" size=20>"
print "Account: <select name=account size=1>"
print "<option " tosel["4000"] "> 4000  Sales Services          "
print "<option " tosel["4100"] "> 4100  Sales Products          "
print "<option " tosel["4200"] "> 4200  Commissions             "
print "<option " tosel["4500"] "> 4500  Other Income            "
print "<option " tosel["1500"] "> 1500  Furniture & Fixtures    "
print "<option " tosel["1510"] "> 1510  Equipment               "
print "<option " tosel["1520"] "> 1520  Reference Library       "
print "<option " tosel["1530"] "> 1530  Vehicle(s)              "
print "<option " tosel["1540"] "> 1540  Computer Hardware       "
print "<option " tosel["1550"] "> 1550  Computer Software       "
print "<option " tosel["1560"] "> 1560  Chattels                "
print "<option " tosel["1000"] "> 1000  Bank General            "
print "<option " tosel["1100"] "> 1100  GST Paid                "
print "<option " tosel["1200"] "> 1200  Accounts Receivable     "
print "<option " tosel["1010"] "> 1010  Cash on Hand            "
print "<option " tosel["1020"] "> 1020  Prepaid Federal Taxes   "
print "<option " tosel["1030"] "> 1030  Prepaid Provincial Taxes"
print "<option " tosel["1040"] "> 1040  Inventory               "
print "<option " tosel["1300"] "> 1300  Notes Receivable        "
print "<option " tosel["1600"] "> 1600  Elig. Capital Property  "
print "<option " tosel["1610"] "> 1610  Organizational Expenses "
print "<option " tosel["1050"] "> 1050  Prepaid Expenses        "
print "<option " tosel["2100"] "> 2100  GST Collected           "
print "</select>"
print "</pre>"
print "<input type=submit value=\"Submit entry\">"
print "<input type=reset value=\"Clear entry\">"
print "</form>"
print "<hr>"
print "</body></html>"
}
